config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'game' => 'pages#game'
  get 'leaderboard' => 'pages#leaderboard'
  
  post   '/leaderboard',  to: 'sessions#create'
  post   '/',  to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  
  resources :users, :predictions

end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
    
    validates :teamScore1, presence: true
    validates :teamScore2, presence: true
    validates :firstScorer, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    COUNTRIES = ['Ireland', 'England']
    
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6, maximum: 50}, allow_nil: true
    validates :country, presence: true
     
    # Returns the hash digest of the given string.
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                         BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
   # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
   # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def game
    @user = User.new
    @currentUser =  current_user
    @predictions = Prediction.new
    @players=Player.all
  end
  
  def home
    @user = User.new
    @currentUser =  current_user
  end

  def leaderboard
    @user = User.new
    @currentUser =  current_user
    @users = User.all.order('points DESC')
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    
    def create
        @player = Player.new(player_params)
        if @player.save
            redirect_to root_path
        else
            redirect_to root_path
        end
    end 
    
    
    private

    def player_params
      params.require(:prediction).permit(:name, :teamID, :position, :playChance)
    end
    
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
    
     def create
        @predictions = Prediction.new(prediction_params)
        if @predictions.save
            flash[:success] = "Prediction Made!"
            redirect_to root_path
        else
            flash[:danger] = "Prediction Unsuccessful! Leave No Fields Blank!"
            redirect_to root_path
        end
     end
    
    
    private

    def prediction_params
      params.require(:prediction).permit(:teamScore1, :teamScore2, :firstScorer)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        log_in user
        flash[:success] = "Sign in Successful"
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_to root_path
      else
        flash[:danger] = "Sign in Unsuccessful, Invalid email/password combination"
        redirect_to root_path
      end
    end
  
  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
     def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Sign up Successful"
            log_in @user
            redirect_to root_path
        else
            flash[:danger] = "Sign up Unsuccessful"
            redirect_to root_path
        end
     end
     
    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
          flash[:success] = "Update Successful"
          redirect_to root_path   
        else
            flash[:danger] = "Update Unsuccessful"
            redirect_to root_path
        end
    end
    
    
    private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
    # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
   # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
   # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="user_header">
        <% if logged_in? %>
          Logged in as <%= current_user.name %>
        <% else%>
          Please log in to make a prediction
        <% end %>
      </div>
      
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   root_path %></li>
          <li><%= link_to "Game",   game_path %></li>
          <li><%= link_to "Leaderboard",   leaderboard_path %></li>
          <% if logged_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Update Profile","#", data: {toggle: "modal", target: "#update"} %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                </ul>
              </li>
          <% else%>
              <li><button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">Sign Up/ Sign In</button></li>
          <% end %>
          
        </ul>
      </nav>
    </div>
  </header>
  <%= render 'layouts/modal' %>
  <%= render 'layouts/update' %>
  
  

app/views/layouts/_modal.html.erb
<!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#sign_up">Sign Up</a></li>
            <li><a data-toggle="tab" href="#sign_in">Sign In</a></li>
          </ul>
        <div class="modal-body">
          <div class="tab-content">
            <div id="sign_up" class="tab-pane fade in active">
              <h1 class="modal-title" id="myModalLabel">Sign Up</h1>
              <div class="form">
                <%= form_for @user do |f| %>
                   <%= render 'shared/error_messages' %>
                 
                  <%= f.text_field :name, :placeholder => "Name", class: 'form-control' %>
                  
                 
                  <%= f.email_field :email, :placeholder => "Email", class: 'form-control' %>
                  
                  <%= f.password_field :password , :placeholder => "Password (6-20 Characters)", class: 'form-control' %>
                 
                  <%= f.password_field :password_confirmation , :placeholder => "Password Confirmation", class: 'form-control' %>
                 
                  <br>
                  <%= f.label :country, class: 'label-style' %>
                  <%= f.collection_select :country, User::COUNTRIES, :to_s, :to_s, :include_blank => true%>
                  
                  <br>
                  <%= f.submit "Create my account", class: "btn btn-primary btn-lg" %>
                <% end %>
      
              </div>
            </div>
            
            <div id="sign_in" class="tab-pane fade">
              
              <h1 class="modal-title" id="myModalLabel">Sign In</h1>
              <div class="form">
                <%= form_for :session do |f| %>
                   <%= render 'shared/error_messages' %>

                  <%= f.email_field :email, :placeholder => "Email", class: 'form-control' %>
                  
                  <%= f.password_field :password , :placeholder => "Password (6-20 Characters)", class: 'form-control' %>
                  
                  <br>
                  <%= f.label :remember_me, class: "checkbox inline" do %>
                    <%= f.check_box :remember_me %>
                    <span>Remember me on this computer</span>
                  <% end %>
                 
                  <%= f.submit "Sign in", class: "btn btn-primary btn-lg" %>
                <% end %>
      
              </div>
            </div>
          </div>
          
       </div>
      </div>
    </div>
  </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
 <![endif]-->

app/views/layouts/_update.html.erb
<!-- Modal -->
 <div class="modal fade" id="update" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
                <% if logged_in? %>
                  <h1 class="modal-title" id="myModalLabel">Update Profile</h1>
                  <div class="form">
                    <%= form_for @currentUser do |f| %>
                       <%= render 'shared/error_messages' %>
                     
                      <%= f.text_field :name, :placeholder => "Name", class: 'form-control' %>
                      
                     
                      <%= f.email_field :email, :placeholder => "Email", class: 'form-control' %>
                      
                      <%= f.password_field :password , :placeholder => "Password (6-20 Characters)", class: 'form-control' %>
                     
                      <%= f.password_field :password_confirmation , :placeholder => "Password Confirmation", class: 'form-control' %>
                     
                      <br>
                      <%= f.label :country, class: 'label-style' %>
                      <%= f.collection_select :country, User::COUNTRIES, :to_s, :to_s, :include_blank => true%>
                      
                      <br>
                      <%= f.submit "Update Profile", class: "btn btn-primary btn-lg" %>
                    <% end %>
          
                  </div>
                <% end %>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Sportego Score Prediction</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %>
  
</head>
<body>
  <%= render 'layouts/header' %>
  
  
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/game.html.erb
<% provide(:title, 'Game') %>
<h1>Game</h1>
<% currentPlayer="None" %>

<div class="form">
        <%= form_for @predictions do |f| %>
           <%= render 'shared/error_messages' %>
          
         <div class = "row">
             <section class="col-sm-4">
          <%= f.number_field :teamScore1, :placeholder => "-", min: 0,max:99, class: 'form-control' %> 
              </section>
              <section class="col-sm-4">
              <p>V</p>
              </section>
              <section class="col-sm-4">
          <%= f.number_field :teamScore2, :placeholder => "-", min: 0,max:99, class: 'form-control' %>
              </section>
              
              <br>
              <h3>First Scorer</h3>
              <!-- Modal -->
<div class="modal fade" id="scoreModal" tabindex="-1" role="dialog" aria-labelledby="scorer" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="scorer">Players</h4>
      </div>
      <div class="modal-body">
        <!--  Player scroll Box  -->
          <ul class="nav nav-pills">
            <li class="active"><a data-toggle="pill" href="#team1">Team 1</a></li>
            <li><a data-toggle="pill" href="#team2">Team 2</a></li>
          </ul>
          
          <div class="tab-content">
            <div id="team1" class="tab-pane fade in active">
            
              <div class="player_scroll_box">
                <h2>Team 1</h2>
                <ol>
                  <%for i in 1..11%>
                   <center><%= radio_button_tag(:playerButton, @players.find(i).name) %> <%=@players.find(i).name%></center><br>
                  
                  <%end%>
                </ol>
              
              </div>
            </div>
            
            <div id="team2" class="tab-pane fade">
              <div class="player_scroll_box">
                <h2>Team 2</h2>
                
                  <%for i in 12..22%>
                   <center><%= radio_button_tag(:playerButton, @players.find(i).name) %> <%=@players.find(i).name%></center><br>
                  
                  <%end%>
                
              
              </div>
            
            </div>
          </div>
        
      
      </div>
      <div class="modal-footer">
        <center> <button onclick = "pick_player()" data-dismiss="modal">Pick Player</button></center> 
      </div>
      </div>
     
    </div>
  </div>

          <%= f.text_field :firstScorer , :value => currentPlayer, :id => 'player_field', class: 'form-control', :readonly => true %>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#scoreModal">Choose Player</button>
         </div>
          <br>
         
          <%= f.submit "Make Prediction", class: "btn btn-primary btn-lg" %>
          
        <% end %>
        <br>
        
      </div>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>Home</h1>

app/views/pages/leaderboard.html.erb
<% provide(:title, 'Leaderboard') %>
<h1>Leaderboard</h1>

<ol class="leaderboard">
  <% @users.each do |user| %>
    
    <div class = "row">
        <section class="col-sm-1">
        <li>
        </section>
        <section class="col-sm-4">
          <%= user.name %>
        </section>
        
        <section class="col-sm-5">
          
        </section>
        
        <section class="col-sm-2">
          <%= user.points %>
        </section>
      
      </li>
    </div>
  <% end %>
</ol>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>